# Generated by Django 5.2.13 on 2026-05-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Email',
            new_name='email',
        ),
    ]
