# Generated by Django 5.2.13 on 2026-05-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_email_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Phone',
            new_name='phone',
        ),
    ]
