# Generated by Django 5.2.13 on 2026-05-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cate_Name', models.CharField(max_length=100, unique=True)),
                ('SLug', models.SlugField(max_length=100, unique=True)),
                ('Cate_Des', models.TextField(blank=True, max_length=200)),
                ('Cate_Img', models.ImageField(blank=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
